"""create tool and profile associations

Revision ID: 1dbcd1fcc22d
Revises: 6c7a0abf873e
Create Date: 2026-09-03 15:37:28.795233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1dbcd1fcc22d"
down_revision: str | Sequence[str] | None = "6c7a0abf873e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_definitions",
        sa.Column("tool_id", sa.Text(), nullable=False),
        sa.Column("risk", sa.Text(), nullable=False),
        sa.Column("parameters_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "allowed_roles",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "requires_approval", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "risk <> 'high' OR requires_approval", name="ck_tool_definitions_high_risk_approval"
        ),
        sa.CheckConstraint("risk IN ('low', 'medium', 'high')", name="ck_tool_definitions_risk"),
        sa.PrimaryKeyConstraint("tool_id"),
    )
    op.create_table(
        "agent_profile_knowledge_bases",
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("knowledge_base_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"], ["knowledge_bases.knowledge_base_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["agent_profiles.profile_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "knowledge_base_id"),
    )
    op.create_table(
        "agent_profile_tools",
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("tool_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["agent_profiles.profile_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["tool_definitions.tool_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("profile_id", "tool_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_profile_tools")
    op.drop_table("agent_profile_knowledge_bases")
    op.drop_table("tool_definitions")
    # ### end Alembic commands ###
