"""create source table

Revision ID: 6264ab7ea8cd
Revises: 2d75432a0aa6
Create Date: 2026-09-02 19:26:17.626928

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6264ab7ea8cd"
down_revision: str | Sequence[str] | None = "2d75432a0aa6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("knowledge_base_id", sa.Text(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("checksum ~ '^[0-9a-f]{64}$'", name="ck_sources_checksum_sha256"),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"], ["knowledge_bases.knowledge_base_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sources")
    # ### end Alembic commands ###
