"""create chunk vector table

Revision ID: 6c7a0abf873e
Revises: 6264ab7ea8cd
Create Date: 2026-09-02 19:44:40.495923

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c7a0abf873e"
down_revision: str | Sequence[str] | None = "6264ab7ea8cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_sources_id_knowledge_base", "sources", ["source_id", "knowledge_base_id"]
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("knowledge_base_id", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(dim=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("chunk_index >= 0", name="ck_chunks_index_non_negative"),
        sa.ForeignKeyConstraint(
            ["source_id", "knowledge_base_id"],
            ["sources.source_id", "sources.knowledge_base_id"],
            name="fk_chunks_source_namespace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("source_id", "chunk_index", name="uq_chunks_source_index"),
    )
    op.create_index("ix_chunks_knowledge_base_id", "chunks", ["knowledge_base_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_knowledge_base_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_constraint("uq_sources_id_knowledge_base", "sources", type_="unique")

    # ### end Alembic commands ###
