"""create prompt and profile tables

Revision ID: a50e73f1f0ad
Revises: 2be740bee36d
Create Date: 2026-09-02 18:58:39.722593

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a50e73f1f0ad"
down_revision: str | Sequence[str] | None = "2be740bee36d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_version_id", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "variables",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("prompt_version_id"),
    )
    op.create_table(
        "agent_profiles",
        sa.Column("profile_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("prompt_version_id", sa.Text(), nullable=False),
        sa.Column("budget_policy_id", sa.Text(), nullable=False),
        sa.Column("approval_policy_id", sa.Text(), nullable=False),
        sa.CheckConstraint("version >= 1", name="ck_agent_profiles_version_positive"),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"], ["prompt_versions.prompt_version_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_profiles")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
